import { useEffect, useRef, useState } from 'react'
const colors=['#ff6ab0','#e91e8c','#9b59b6','#f39c12','#e74c3c','#56e39f','#65b7ff','#ffffff','#ff8a65','#f5c2ff']
export default function DrawingCanvas({height=300,onSave,background='#0d0118',image}){const ref=useRef(null);const drawing=useRef(false);const [color,setColor]=useState(colors[0]);const [size,setSize]=useState(5);const [tool,setTool]=useState('pen')
useEffect(()=>{const c=ref.current,x=c.getContext('2d');x.fillStyle=background;x.fillRect(0,0,c.width,c.height);if(image){const i=new Image();i.crossOrigin='anonymous';i.onload=()=>x.drawImage(i,0,0,c.width,c.height);i.src=image}},[background,image])
const point=e=>{const r=ref.current.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*ref.current.width/r.width,y:(p.clientY-r.top)*ref.current.height/r.height}}
const start=e=>{e.preventDefault();drawing.current=true;const p=point(e),x=ref.current.getContext('2d');x.beginPath();x.moveTo(p.x,p.y)}
const move=e=>{if(!drawing.current)return;e.preventDefault();const p=point(e),x=ref.current.getContext('2d');x.lineCap='round';x.lineJoin='round';x.globalAlpha=tool==='marker'?.6:1;x.strokeStyle=tool==='eraser'?background:color;x.lineWidth=tool==='marker'?size*3:size;x.shadowBlur=tool==='pen'?10:0;x.shadowColor=color;x.lineTo(p.x,p.y);x.stroke()}
const end=e=>{e?.preventDefault();drawing.current=false;const x=ref.current.getContext('2d');x.closePath();x.globalAlpha=1;x.shadowBlur=0}
const clear=()=>{const x=ref.current.getContext('2d');x.fillStyle=background;x.fillRect(0,0,ref.current.width,ref.current.height)}
return <div><canvas ref={ref} width="800" height="600" className="w-full rounded-2xl border border-pink/20 bg-bg" style={{height,touchAction:'none'}} onMouseDown={start} onMouseMove={move} onMouseUp={end} onMouseLeave={end} onTouchStart={start} onTouchMove={move} onTouchEnd={end}/><div className="mt-3 flex gap-2">{[['pen','✏️ Pen'],['marker','🖌️ Marker'],['eraser','⬜ Eraser']].map(([v,l])=><button key={v} onClick={()=>setTool(v)} className={`tap rounded-full px-3 py-1.5 text-xs ${tool===v?'bg-pink text-white':'bg-purple/20 text-muted'}`}>{l}</button>)}</div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{colors.map(c=><button key={c} aria-label={c} onClick={()=>setColor(c)} className={`h-7 w-7 shrink-0 rounded-full border-2 ${color===c?'border-white':'border-transparent'}`} style={{background:c}}/>)}</div><label className="mt-3 flex items-center gap-3 text-xs text-muted">Brush size<input type="range" min="2" max="22" value={size} onChange={e=>setSize(+e.target.value)} className="accent-pink"/></label><div className="mt-4 flex gap-2"><button onClick={clear} className="secondary-btn flex-1">Clear</button>{onSave&&<button onClick={()=>onSave(ref.current.toDataURL('image/png'))} className="primary-btn flex-1">Save Doodle</button>}</div></div>}
